name: gnl test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install paco
        run: sudo bash -c "$(curl -fsSL https://raw.github.com/xicodomingues/francinette/master/bin/install.sh)"
      - name: norm
        run: | 
          sudo python3 -m pip install --upgrade pip setuptools && python3 -m pip install norminette
          sudo python3 -m pip install --upgrade norminette
      - name: check
        run: time norminette */*.[c/h]
        
